### ISSUE TITLE
Refreshing Docker environment with up-to-date repository leads to malformed HTTP header 

### ISSUE THREAD

**Issue by znk** [openwhyd/openwhyd#105]
The following error appears preventing from interacting with the web application:
```
Error: bad content-type header, no content-type
    at IncomingForm._parseContentType (/usr/src/app/node_modules/formidable/lib/incoming_form.js:219:17)
    at IncomingForm.writeHeaders (/usr/src/app/node_modules/formidable/lib/incoming_form.js:131:8)
    at IncomingForm.parse (/usr/src/app/node_modules/formidable/lib/incoming_form.js:84:8)
    at constructor.bodyParser (/usr/src/app/app/lib/my/http/Application.js:110:12)
    at prepareResponse (/usr/src/app/app/lib/my/http/Application.js:236:8)
    at _checkRoutes (/usr/src/app/app/lib/my/http/Application.js:281:9)
    at constructor.<anonymous> (/usr/src/app/app/lib/my/http/Application.js:64:9)
    at emitTwo (events.js:106:13)
    at constructor.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
```

It is the same in console:
``` 
mongo_1  | 2017-10-09T09:10:04.167+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58632 #5 (5 connections now open)
web_1    |  - found table: activity : 0 rows
web_1    |  - found table: plContest : 0 rows
web_1    |  - found table: fbfriends : 0 rows
web_1    |  - found table: email : 0 rows
web_1    |  - found table: comment : 0 rows
web_1    |  - found table: collabPl : 0 rows
web_1    | MongoDB model is now ready for queries!
web_1    | Caching users ...
web_1    | loading EMAIL module: emailFake.js...
web_1    | loading SEARCH module: searchAlgolia...
web_1    | Parsing reserved usernames from config/app.route ...
web_1    | Parsing reserved usernames from config/reservedwords.txt ...
web_1    | Caching users: done!
web_1    | /bin/sh: 1: gm: not found
web_1    | [my.img] detected Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-15 http://www.imagemagick.org => using it for image manipulation
web_1    | my.img:USE_GRAPHICS_MAGICK = false
web_1    | Server running at http://127.0.0.1:8080/
web_1    | [DIGEST WORKER] config.digestInterval is NULL or NEGATIVE => digest worker is disabled
web_1    | [HOT SNAPSHOT WORKER] Starting with interval ...
web_1    | plTags.tagEngine: building playlists list...
web_1    | => Parsed 133 handles from: config/app.route
mongo_1  | 2017-10-09T09:10:04.453+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58634 #6 (6 connections now open)
web_1    | => Parsed 299 handles from: config/reservedwords.txt
web_1    | current iPhone versions: { openwhydServerVersion: '1.0.10',
web_1    |   decodeVer: 1507540152511,
web_1    |   iphoneAppVer: 0 }
web_1    | plTags.tagEngine => extracted tags from 0 / 0 playlists, from 0 users, in 0.023 seconds
web_1    | plTags.tagEngine: indexing eId-tags from playlist names...
web_1    | plTags.tagEngine => indexed  0 eId-tags from playlist names, in 0.045 seconds
web_1    | plTags.tagEngine: indexing users for each tag...
web_1    | plTags.tagEngine => indexed 0 users from 0 posts, in 0.002 seconds
web_1    | error Error: bad content-type header, no content-type
web_1    |     at IncomingForm._parseContentType (/usr/src/app/node_modules/formidable/lib/incoming_form.js:219:17)
web_1    |     at IncomingForm.writeHeaders (/usr/src/app/node_modules/formidable/lib/incoming_form.js:131:8)
web_1    |     at IncomingForm.parse (/usr/src/app/node_modules/formidable/lib/incoming_form.js:84:8)
web_1    |     at constructor.bodyParser (/usr/src/app/app/lib/my/http/Application.js:110:12)
web_1    |     at prepareResponse (/usr/src/app/app/lib/my/http/Application.js:236:8)
web_1    |     at _checkRoutes (/usr/src/app/app/lib/my/http/Application.js:281:9)
web_1    |     at constructor.<anonymous> (/usr/src/app/app/lib/my/http/Application.js:64:9)
web_1    |     at emitTwo (events.js:106:13)
web_1    |     at constructor.emit (events.js:191:7)
web_1    |     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
web_1    | error Error: bad content-type header, no content-type
web_1    |     at IncomingForm._parseContentType (/usr/src/app/node_modules/formidable/lib/incoming_form.js:219:17)
web_1    |     at IncomingForm.writeHeaders (/usr/src/app/node_modules/formidable/lib/incoming_form.js:131:8)
web_1    |     at IncomingForm.parse (/usr/src/app/node_modules/formidable/lib/incoming_form.js:84:8)
web_1    |     at constructor.bodyParser (/usr/src/app/app/lib/my/http/Application.js:110:12)
web_1    |     at prepareResponse (/usr/src/app/app/lib/my/http/Application.js:236:8)
web_1    |     at _checkRoutes (/usr/src/app/app/lib/my/http/Application.js:281:9)
web_1    |     at constructor.<anonymous> (/usr/src/app/app/lib/my/http/Application.js:64:9)
web_1    |     at emitTwo (events.js:106:13)
web_1    |     at constructor.emit (events.js:191:7)
web_1    |     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
```

**Comment by znk** [comment]
It had to do with Docker cache, solved.
