### ISSUE TITLE
invalid mongodb object id:undefined, from incrPlayCounter()

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#179]
**Describe the bug**

The production server's stderr logs contains many entries like this one:

```
Sat, 27 Oct 2018 20:14:52 GMT, Warning (concise trace)
    at exports.ObjectId (/home/adrien/openwhyd/app/models/mongodb.js:39:13)
    at Object.exports.incrPlayCounter (/home/adrien/openwhyd/app/models/post.js:421:13)
    at Object.incrPlayCounter (/home/adrien/openwhyd/app/controllers/api/post.js:237:20)
    at Object.exports.handleRequest (/home/adrien/openwhyd/app/controllers/api/post.js:282:38)
    at Object.exports.controller [as post] (/home/adrien/openwhyd/app/controllers/api/post.js:293:11)
    at constructor.exports.controller (/home/adrien/openwhyd/app/controllers/subdir.js:23:38)
    at /home/adrien/openwhyd/app/lib/my/http/Application.js:298:33
    at /home/adrien/openwhyd/app/lib/my/session/index.js:130:7
invalid mongodb object id:undefined
```

**Comment by adrienjoly** [comment]
I see that there were ~10k emails sent from our shared SendGrid account, on 11/10/2018:

![image](https://user-images.githubusercontent.com/531781/47609511-52665380-da40-11e8-9573-fbe47bd2e79e.png)

=> Hypothesis: this spike may have caused our SendGrid account to go overquota, and/or our outgoing email requests to be throttled / rate limited.

**Comment by adrienjoly** [comment]
after fixing this problem, let's let these errors be thrown instead of catching them.

**Comment by adrienjoly** [comment]
Failure cases:

- empty string from `incrPlayCounter`:

<img width="818" alt="image" src="https://github.com/openwhyd/openwhyd/assets/531781/5726cddc-2884-479a-89fa-6f6f1de8f30f">

- 32-byte identifier from a `uCoverImg` URL:

<img width="854" alt="image" src="https://github.com/openwhyd/openwhyd/assets/531781/c52a0557-1c25-4199-9d21-0bb8af3d53fe">
