### ISSUE TITLE
2 "notif" unit tests are failing

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#212]
**To Reproduce**
- run `$ npm run test-unit`
=> 2 tests fail

```
npm run test-unit

> openwhyd@1.11.2 test-unit /Users/adrienjoly/Dev/_adrienjoly/openwhyd
> mocha test/unit/*.js --exit

models.search: DISABLED (see config.enableSearchIndex)
models.search: NO IMPLEMENTATION for init
models.search: NO IMPLEMENTATION for query
models.search: NO IMPLEMENTATION for init
Parsing reserved usernames from config/app.route ...
Parsing reserved usernames from config/reservedwords.txt ...
loading EMAIL module: emailFake.js...


  email validation
=> Parsed 299 handles from: config/reservedwords.txt
=> Parsed 69 handles from: config/app.route
    ✓ should allow email@domain.com
    ✓ should not allow a non-string value
    ✓ should allow tools@symbol.agency (new tld)

  notif
Connecting to mongodb://localhost:27017/openwhyd_test...
Successfully connected to mongodb://localhost:27017/openwhyd_test
Applying db init script: ./config/initdb.js ...
[mongo shell] creating openwhyd collections...
[mongo shell] indexing post collection...
[mongo shell] indexing follow collection...
[mongo shell] indexing user collection...
[mongo shell] indexing track collection...
[mongo shell] indexing collabPl collection...
[mongo shell] indexing notif collection...
[mongo shell] done! :-)
 - found table: track : 0 rows
 - found table: invite : 0 rows
 - found table: user : 0 rows
 - found table: plContest : 0 rows
 - found table: email : 0 rows
 - found table: post : 0 rows
 - found table: config : 0 rows
 - found table: notif : 0 rows
 - found table: follow : 0 rows
 - found table: collabPl : 0 rows
 - found table: featured : 0 rows
 - found table: comment : 0 rows
 - found table: activity : 0 rows
MongoDB model is now ready for queries!
Caching users ...
Caching users: done!
    ✓ initiatialises db (284ms)
found 0 empty notifs in db
    ✓ clean notifications db
found 0 notifs in db
    ✓ clear all notifications (511ms)
push notif prefs not found for user:  undefined
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
push notif prefs not found for user:  undefined
push notif prefs not found for user:  undefined
push notif prefs not found for user:  undefined
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
    1) add sample notifications
found 0 notifs in db
    ✓ clear all notifications (503ms)
found 0 empty notifs in db
    ✓ check that db is clean
push notif prefs not found for user:  undefined
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
push notif prefs not found for user:  undefined
push notif prefs not found for user:  undefined
push notif prefs not found for user:  undefined
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
found 6 notifs in db
    2) add sample notifications (again)
found 6 notifs in db
found 0 notifs in db
    ✓ clear individual notifications (507ms)
found 0 empty notifs in db
    ✓ check that db is clean
    ✓ call notif.sendTrackToUsers() with no parameters [should fail]
    ✓ call notif.sendTrackToUsers() without pId parameter [should fail]
    ✓ call notif.sendTrackToUsers() with a object-typed pId parameter [should fail]
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
found 1 notifs in db
found 1 notifs in db
    ✓ gilles sends a track to me (507ms)
found 0 notifs in db
    ✓ clear all notifications (509ms)
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
found 1 notifs in db
found 1 notifs in db
    ✓ gilles sends a playlist to me (509ms)
found 0 notifs in db
    ✓ clear all notifications (504ms)
push notif prefs not found for user:  4d94501d1f78ac091dbc9b4d
    ✓ gilles sends a track to me => res._id is populated
found 0 notifs in db
    ✓ clear all notifications (508ms)

  snip.js
    ✓ translateFields() should replace a mapped field
    ✓ translateFields() should not crash on an object without prototype

  "get" package
    ✓ should provide the title of a web page
(node:40453) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ should provide the title of a web page encoded with an iso-2022-jp charset (57ms)
    ✓ should provide the images of a web page

  "img" package
/bin/sh: gm: command not found
/bin/sh: convert: command not found
[my.img] ERROR: please install graphicsmagick or imagemagick for image manipulation.
    3) should create a thumb

  track matcher
    ✓ should not match very different tracks
    ✓ should match tracks with close metadata


  26 passing (13s)
  3 failing

  1) notif
       add sample notifications:
     Error: failed
      at cb (test/unit/notif-tests.js:374:16)
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:112:11
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:128:9
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:121:7
      at Object.exports.getUserNotifs (app/models/notif.js:263:21)
      at fetchNotifs (test/unit/notif-tests.js:119:16)
      at checkNotifs (test/unit/notif-tests.js:127:7)
      at Timeout.<anonymous> (test/unit/notif-tests.js:108:7)

  2) notif
       add sample notifications (again):
     Error: failed
      at cb (test/unit/notif-tests.js:374:16)
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:112:11
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:128:9
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/notif-tests.js:121:7
      at Object.exports.getUserNotifs (app/models/notif.js:263:21)
      at fetchNotifs (test/unit/notif-tests.js:119:16)
      at checkNotifs (test/unit/notif-tests.js:127:7)
      at Timeout.<anonymous> (test/unit/notif-tests.js:108:7)

  3) "img" package
       should create a thumb:

      Uncaught AssertionError [ERR_ASSERTION]: uniqueHash_thumb.jpg should be created by img.makeThumb()
      + expected - actual

      -false
      +true
      
      at /Users/adrienjoly/Dev/_adrienjoly/openwhyd/test/unit/unit-tests.js:125:7
      at execCallback (app/lib/my-img/index.js:88:24)
      at ChildProcess.exithandler (child_process.js:301:5)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

Note: you can ignore the 3rd failing test because I just did not install the corresponding dependency.

**Comment by adrienjoly** [comment]
Work in progress: https://github.com/openwhyd/openwhyd/tree/fix-unit-tests
