### ISSUE TITLE
Errors during start script (npm run run)

### ISSUE THREAD

**Issue by greyvugrin** [openwhyd/openwhyd#30]
Getting the following output when booting up the app:

```
openwhyd@0.1.0 run /Users/greyvugrin/Desktop/code/openwhyd/whydJS
> node app.js --color --fakeEmail --digestInterval -1 $@

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Starting web server with params: { dev: 'true',
  port: '8080',
  urlPrefix: 'http://localhost:8080',
  mongoDbHost: 'localhost',
  mongoDbPort: '27017',
  mongoDbAuthUser: '',
  mongoDbAuthPassword: '',
  mongoDbDatabase: 'openwhyd_data',
  genuineSignupSecret: '',
  searchModule: 'searchAlgolia',
  advertisePlaylistContestOnHome: false,
  emailModule: '',
  digestInterval: '-1',
  digestImmediate: false,
  feedbackEmail: 'greyvugrin@gmail.com',
  version: 25,
  startTime: 2017-01-01T00:06:01.588Z,
  nbPostsPerNewsfeedPage: 20,
  nbTracksPerPlaylistEmbed: 100,
  paths:
   { whydPath: '../whydJS',
     uploadDirName: 'upload_data',
     uAvatarImgDirName: 'uAvatarImg',
     uCoverImgDirName: 'uCoverImg',
     uPlaylistDirName: 'uPlaylistImg' },
  color: true }
Connecting to mongodb://localhost:27017/openwhyd_data...
===
Sun, 01 Jan 2017 00:06:01 GMT Error
    at Console.error (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/app.js:16:45)
    at process.on (internal/process/warning.js:24:17)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.nextTick (internal/process/warning.js:47:38)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
(node:47208) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
Successfully connected to mongodb://localhost:27017/openwhyd_data
 - found table: visit : 0 rows
 - found table: post : 0 rows
 - found table: track : 0 rows
 - found table: comment : 0 rows
 - found table: config : 0 rows
 - found table: follow : 0 rows
 - found table: plContest : 0 rows
 - found table: email : 0 rows
 - found table: invite : 0 rows
 - found table: notif : 0 rows
 - found table: featured : 0 rows
 - found table: collabPl : 0 rows
 - found table: activity : 0 rows
 - found table: user : 0 rows
 - found table: playlog : 0 rows
 - found table: fbfriends : 0 rows
Caching users ...
loading EMAIL module: emailFake.js...
FAKE EMAIL ENABLED, duration:  2000  milliseconds
[APNS] parameters: { cert: '/Users/greyvugrin/Desktop/code/openwhyd/whydJS/app/models/../../config/apns/aps_dev.cert.pem',
  key: '/Users/greyvugrin/Desktop/code/openwhyd/whydJS/app/models/../../config/apns/aps_dev.key.pem',
  passphrase: '',
  gateway: 'gateway.sandbox.push.apple.com',
  port: 2195,
  production: false }
[APNS] Connecting...
loading SEARCH module: searchAlgolia...
models.search: using Algolia Search index
Parsing reserved usernames from config/app.route ...
Parsing reserved usernames from config/reservedwords.txt ...
MongoDB model is now ready for queries!
Caching users: done!
- Local -
[mainTemplate] today is week # 313
/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
        ^

ReferenceError: fs is not defined
    at module.exports (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/my/session/index.js:10:34)
    at start (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/app.js:133:49)
    at /Users/greyvugrin/Desktop/code/openwhyd/whydJS/app/models/mongodb.js:83:17
    at /Users/greyvugrin/Desktop/code/openwhyd/whydJS/app/models/user.js:201:4
    at /Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/cursor.js:180:16
    at commandHandler (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/cursor.js:734:16)
    at /Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/connection/base.
js:453:41)
    at /Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/Users/greyvugrin/Desktop/code/openwhyd/whydJS/node_modules/mongodb/lib/mongodb/responses/mongo_repl
y.js:68:5)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "run"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! openwhyd@0.1.0 run: `node app.js --color --fakeEmail --digestInterval -1 $@`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openwhyd@0.1.0 run script 'node app.js --color --fakeEmail --digestInterval -1 $@'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openwhyd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js --color --fakeEmail --digestInterval -1 $@
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openwhyd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openwhyd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greyvugrin/Desktop/code/openwhyd/whydJS/npm-debug.log
```

I have my DB set up, make and g++ are installed. I am missing some env vars for algolia and sendgrid but doubt that those are causing this. Thanks in advance!

**Comment by adrienjoly** [comment]
Did you run `npm install` ?

Or you did, please use `nvm` to switch to the nodejs version (`engine`) specified in `package.json`, and retry to install dependencies with `npm install`.

**Comment by greyvugrin** [comment]
Worked like a charm - running smoothly now!
