### ISSUE TITLE
Can't follow user

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#441]
**To Reproduce**

1. Go to https://openwhyd.org/u/6016705008ced3543d21bb2f
2. Click on "follow" => nothing happens, except an error in the JavaScript console:

```
GET https://openwhyd.org/api/follow?action=insert&tId=6016705008ced3543d21bb2f&_=1612123540712 => 404
```

**Comment by adrienjoly** [comment]
from node.js logs, when reproducing the API call locally:

```
web_1    | ▶ 2021-02-07T15:53:30.748Z GET /api/follow?action=insert&tId=58fd0b7998267ba4b34b73f2&_=1612712987922 (follow.controller) {"_subCtr":"follow","action":"insert","tId":"58fd0b7998267ba4b34b73f2","_":"1612712987922"}
web_1    | ❌ Error -- Sun, 07 Feb 2021 15:53:30 GMT [subdir] error while contacting /api/follow?action=insert&tId=58fd0b7998267ba4b34b73f2&_=1612712987922 TypeError: Update document requires atomic operators
web_1    |     at new UpdateOneOperation (/usr/src/app/node_modules/mongodb/lib/operations/update_one.js:12:13)
web_1    |     at Collection.updateOne (/usr/src/app/node_modules/mongodb/lib/collection.js:758:5)
web_1    |     at Object.exports.add (/usr/src/app/app/models/follow.js:70:14)
web_1    |     at follow (/usr/src/app/app/controllers/api/follow.js:24:19)
web_1    |     at exports.controller (/usr/src/app/app/controllers/api/follow.js:138:3)
web_1    |     at Object.exports.controller (/usr/src/app/app/controllers/subdir.js:20:5)
web_1    |     at endpointHandler (/usr/src/app/app/lib/my-http-wrapper/http/Application.js:180:27)
web_1    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
web_1    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
web_1    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
web_1    | ◀ 2021-02-07T15:53:30.732Z GET /api/follow responds 404 after 31 ms
```

=> Error: `TypeError: Update document requires atomic operators`

**Comment by adrienjoly** [comment]
According to Datadog, this error has been happening only on `follow` API calls, and since January 29th:

![image](https://user-images.githubusercontent.com/531781/107151906-6dd1a000-6965-11eb-86d5-86832409c6f5.png)
