### ISSUE TITLE
BUG: iPhone app cannot retrieve playlist tracks from API

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#89]
Reported by Arasg:

> quand je veux aller dans mes playlists, j'ai un message qui me dit que je n'ai pas encore ajouté de titres alors que c'est faux...38

Continuation of https://github.com/openwhyd/openwhyd-ios/issues/1

=> API calls made by the iOS app are to be tested on the back-end

**Comment by adrienjoly** [comment]
resolution steps:

- [ ] write a failing API test that creates a playlist with a track, then checks that the playlist contains that track, using same API call as the iPhone app
- [ ] make the test pass by fixing the problem
- [ ] push fix to production and ask Arasg if it solves the problem

**Comment by adrienjoly** [comment]
For reference, the urls of the iOS app's API calls are in that file: https://github.com/openwhyd/openwhyd-ios/blob/d700d5b45242301591fb5f098d1be4153b54f2b2/Whyd/Config.h#L125

**Comment by adrienjoly** [comment]
Getting the following errors in production, when trying to open a playlist from the iOS app:

```bash
$ tail -F appd.err
    at queryCallback (/home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'Failed to parse: { find: "post", filter: { uId: "4d94501d1f78ac091dbc9b4d", pl.id: 61 }, sort: { order: 1, _id: -1 }, limit: "1000,201" }. \'limit\' field must be numeric.',
  waitedMS: 0,
  ok: 0,
  errmsg: 'Failed to parse: { find: "post", filter: { uId: "4d94501d1f78ac091dbc9b4d", pl.id: 61 }, sort: { order: 1, _id: -1 }, limit: "1000,201" }. \'limit\' field must be numeric.',
  code: 9 }








===
Thu, 17 Aug 2017 13:42:21 GMT Error
    at Console.error (/home/adrien/openwhyd/whydJS/app.js:23:45)
    at /home/adrien/openwhyd/whydJS/app/models/post.js:78:13
    at handleCallback (/home/adrien/openwhyd/whydJS/node_modules/mongodb/lib/utils.js:120:56)
    at /home/adrien/openwhyd/whydJS/node_modules/mongodb/lib/cursor.js:857:22
    at handleCallback (/home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at /home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:22
    at queryCallback (/home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:212:16)
    at /home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
model.fetchPosts ERROR on query { uId: '4d94501d1f78ac091dbc9b4d', 'pl.id': 60 } with params { sort: [ [ 'order', 'asc' ], [ '_id', 'desc' ] ],
  limit: '1000,201' } : { MongoError: Failed to parse: { find: "post", filter: { uId: "4d94501d1f78ac091dbc9b4d", pl.id: 60 }, sort: { order: 1, _id: -1 }, limit: "1000,201" }. 'limit' field must be numeric.
    at Function.MongoError.create (/home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/adrien/openwhyd/whydJS/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'Failed to parse: { find: "post", filter: { uId: "4d94501d1f78ac091dbc9b4d", pl.id: 60 }, sort: { order: 1, _id: -1 }, limit: "1000,201" }. \'limit\' field must be numeric.',
  waitedMS: 0,
  ok: 0,
  errmsg: 'Failed to parse: { find: "post", filter: { uId: "4d94501d1f78ac091dbc9b4d", pl.id: 60 }, sort: { order: 1, _id: -1 }, limit: "1000,201" }. \'limit\' field must be numeric.',
  code: 9 }
```

**Comment by adrienjoly** [comment]
WIP: https://github.com/openwhyd/openwhyd/tree/bug-89

**Comment by adrienjoly** [comment]
Progress: was able to reproduce the bug, by providing two values of the same `limit` parameter in the playlist track request: `?...&limit=1000&limit=20`

=> next step: check if the iOS does this.

**Comment by adrienjoly** [comment]
After activating the [logging of GET parameters](https://github.com/openwhyd/openwhyd/commit/d3e517cee80e3d478b941e924b6b2605f4f77a84) of incoming requests on openwhyd.org, I used the iOS app to open a playlist, and observed the following trace:

```
=== Fri, 18 Aug 2017 11:48:07 GMT GET /u/4d94501d1f78ac091dbc9b4d/playlist/61?format=json&limit=1000&limit=20 (userLibrary.controller) {"format":"json","limit":["1000","20"],"id":"4d94501d1f78ac091dbc9b4d","playlistId":"61"}
fetching user  { _id: 4d94501d1f78ac091dbc9b4d } ...
fetchPlaylists: 14.517ms
fetchStats: 11.812ms
fetchLikes: 1.001ms
fetchNbTracks: 9.095ms
=> fetched 0 posts
fetchAndRender: 5.602ms
```

=> the iOS app is indeed sending two values for the `limit` parameter, which is probably causing the bug.

**Comment by adrienjoly** [comment]
Proposed solution:

- The `limit` parameter should not be provided more than once to the API request. => I proposed a fix in the iOS codebase: https://github.com/openwhyd/openwhyd-ios/pull/4 (pending review)
